### ISSUE TITLE
just use news api, no need to parse

### ISSUE THREAD

**Issue by umputun** [malamud/radiot-shownotes-to-mp3#1]
- get last activated articles `GET /api/v1/news/active/last/{hrs}`
example - https://news.radio-t.com/api/v1/news/active/last/8

- the same, but in md - `/api/v1/news/lastmd/{hrs}` (probably you don't need this one)

Response json has all you need, even image link

**Comment by malamud** [comment]
Chat log has timestamps when news was started to discuss and the official cut. 
If I got it correctly, the news api doesn't have this data it has just news metadata.  The show notes doesn't make sense in file without timestamps.
Is there something like that /api/v1/logs/last ?

**Comment by umputun** [comment]
each record has "activets" - time of activation (selection). This is the same time you will see in show notes and should use for your time labels.

for the official cut you shoul use `GET /api/v1/show/start`

**Comment by malamud** [comment]
Got it. Thanks.

**Comment by malamud** [comment]
Done. If news pic is empty use radio-t cover.
